### ISSUE TITLE
crash in WPEFramework

### ISSUE THREAD

**Issue by goruklu** [WebPlatformForEmbedded/Thunder#17] opened 2018-08-17 17:40 UTC
We are seeing crashes in WPEFramework with the following stack trace:
[Stackwalk_Result_BC644B8BD8C8_dat2018-08-16-12-03-34.txt](https://github.com/WebPlatformForEmbedded/WPEFramework/files/2298184/Stackwalk_Result_BC644B8BD8C8_dat2018-08-16-12-03-34.txt)

We'll try to add logs once we capture them.

**Comment by goruklu** [comment] 2018-08-17 17:48
the revisions we are using are:
**wpeframework:**
```
revision date: June 11, 2018
SRCREV = "d4e40417c6247adbe6a034fbbe5dc7a768d506f1"
```

**wpeframework-plugins:**
```
revision date: June 8, 2018
SRCREV = "6c48dfc064171a038cde4370ec4c7721fa16c205"
```

**Comment by goruklu** [comment] 2018-08-17 17:51
Another backtrace:
[resolved_minidump.txt](https://github.com/WebPlatformForEmbedded/WPEFramework/files/2298211/resolved_minidump.txt)

**Comment by goruklu** [comment] 2018-08-17 18:59
it looks like the crashes are occurring at the end of playback. 
We see `** (process:5821): WARNING **: Child process killed by signal 15` printed  in the WPE browser log.

**Comment by pwielders** [comment] 2018-08-17 19:02
Looks like it is closing down. The singletons are being destructed.
Is this the WPEWebKit Process closing down ?

**Comment by pwielders** [comment] 2018-08-17 19:04
First quick analyses is that the singeltons are being destructed but some RPC objects are still in use. So OCDM is still communicating while the WebKit is being torn down. 
WPEFramework keeps on runnning I assume, it is the spawned WPEWebKit process deactivating? Correct?

**Comment by goruklu** [comment] 2018-08-17 19:11
yes, it looks like WPEFramework process is continuing to run, wpewebprocess is deactivating

**Comment by pwielders** [comment] 2018-08-23 08:05
Sorry accidently closed it. The issue is the leak in the webkit: https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-20170728/Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp#L82
The leak is currently initentional as it crashes the WPEWebKit if it becomes a stack variable.
Working on a fix for this.

**Comment by pwielders** [comment] 2018-08-23 20:26
We fixed the issue of the leak on the master. Two commits are required. One in WPEframework and one in Webkit.
WPEFramework:          
https://github.com/WebPlatformForEmbedded/WPEFramework/commit/7e21ad6913342b47060731bc344100699914dce1

WPEWebkit:
https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/e5dfbafc8c0faabea1ac9b6ce04e2619638caf80

**Comment by pwielders** [comment] 2018-08-23 20:27
@goruklu Could you apply these patches on your branches and report back if this resolves the issue on your branches as well?

**Comment by goruklu** [comment] 2018-08-23 20:28
@pwielders thanks for the fix, we'll try them and let you know the results.

**Comment by goruklu** [comment] 2018-08-31 20:40
@pwielders we still see the crash unfortunately.

**Comment by TomMettam** [comment] 2018-08-31 23:36
I am seeing a crash when any media is played. I'm unsure how to get a stack trace from WPE on the raspberry pi

**Comment by woutermeek** [comment] 2019-02-06 12:23
@goruklu are you still seeing this issue?

**Comment by goruklu** [comment] 2019-02-06 22:23
@woutermeek we were still seeing the crash but we have a patch that fixed it for us. 
We are still using pretty old versions of wpeframework and wpeframework-plugins. Currently we are in the process of moving them to the latest revisions. We'll check whether the crashes still occur after the update and let you know.

**Closed** 2019-07-26 08:21 UTC
